name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  new-customer:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run tests for new customer
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        ADMIN_FIRST_NAME: ${{ secrets.ADMIN_FIRST_NAME }}
        ADMIN_LAST_NAME: ${{ secrets.ADMIN_LAST_NAME }}

      run: npm run ui-test-new-customer

    - name: Upload blob report
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: all-blob-reports-new-customer
        path: blob-report/
        retention-days: 5
  
        
  admin:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run tests for admin
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        ADMIN_FIRST_NAME: ${{ secrets.ADMIN_FIRST_NAME }}
        ADMIN_LAST_NAME: ${{ secrets.ADMIN_LAST_NAME }}

      run: npm run ui-test-existing-admin

    - name: Upload blob report
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: all-blob-reports-admin
        path: blob-report/
        retention-days: 5    
      
  existing-customer:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run tests for existing customer
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        EXISTING_CUSTOMER_EMAIL: ${{ secrets.EXISTING_CUSTOMER_EMAIL }}
        EXISTING_CUSTOMER_PASSWORD: ${{ secrets.EXISTING_CUSTOMER_PASSWORD }}
        EXISTING_CUSTOMER_FIRST_NAME: ${{ secrets.EXISTING_CUSTOMER_FIRST_NAME }}
        EXISTING_CUSTOMER_LAST_NAME: ${{ secrets.EXISTING_CUSTOMER_LAST_NAME }}

      run: npm run ui-test-existing-customer

    - name: Upload blob report
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: all-blob-reports-customer
        path: blob-report/
        retention-days: 5
         
  merge-reports:
    if: ${{ !cancelled() }}
    needs: [new-customer, admin, existing-customer]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci

    - name: Download all blob reports
      uses: actions/download-artifact@v4
      with:
        pattern: all-blob-reports-*
        path: all-blobs
        merge-multiple: true

    - name: Merge HTML Report
      run: npx playwright merge-reports --reporter html ./all-blobs

    - name: Upload Final HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: final-playwright-report
        path: playwright-report/
        retention-days: 5